version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
      - 18080:18080
    depends_on:
      - nifi
      - nifi-registry
    volumes:
      - ${NGINX_CONFIG_PATH}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NGINX_CONFIG_PATH}/.htpasswd:/etc/nginx/passwords:ro

  nifi:
    image: 235249841952.dkr.ecr.us-east-1.amazonaws.com/nifi:1.11.4
    container_name: nifi
    hostname: nifi
    ports:
      - "10000-11000:10000-11000"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_db:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_extensions:/opt/nifi/nifi-current/extensions

  nifi-registry:
    image: 235249841952.dkr.ecr.us-east-1.amazonaws.com/nifi-registry:0.6.1
    container_name: nifi-registry
    hostname: nifi-registry
    environment:
      - NIFI_REGISTRY_FLOW_PROVIDER=git
      - NIFI_REGISTRY_GIT_REMOTE=origin

  nifi-mysql-db:
    image: mysql:8.0.21
    container_name: nifi-mysql-db
    hostname: nifi-mysql-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  nifi_conf:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DATA_PATH}/nifi/conf
      o: bind
  nifi_db:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DATA_PATH}/nifi/db
      o: bind
  nifi_flowfile:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DATA_PATH}/nifi/flowfile
      o: bind
  nifi_content:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DATA_PATH}/nifi/contents
      o: bind
    nifi_state:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DATA_PATH}/nifi/state
      o: bind
  nifi_provenance:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DATA_PATH}/nifi/provenance
      o: bind
  nifi_extensions:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DATA_PATH}/nifi/extensions
      o: bind
  mysql-data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DATA_PATH}/mysql-data
      o: bind